spring:
  application:
    name: atlas

  datasource:
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: "user"
      password: "$2a$12$5ZdZG/CicwB3XOO2jznu.ODrann63USsFjYXy8xfd0R0GMjT3HIdC"

management:
  endpoints:
    web:
      exposure:
        include: "*"