spring:
  application:
    name: atlas

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/atlas}
    username: ${DB_NAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true

  cache:
    type: redis
    cache-names:
      - comment
      - user
      - workspace
      - member
      - task
  data:
    redis:
      host: localhost
      port: 6379

  devtools:
    restart:
      enabled: true
  banner:
    location: banner.txt

  mail:
    host: smtp.gmail.com
    port: 587
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    db:
      enabled: true

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate.jpa: warn